# Generated by Django 5.2.7 on 2026-01-22 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unsubscribed', 'Unsubscribed')], db_index=True, default='active', max_length=15)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['email'], name='notificatio_email_65eb20_idx'), models.Index(fields=['status'], name='notificatio_status_7c4483_idx'), models.Index(fields=['subscribed_at'], name='notificatio_subscri_61a15a_idx')],
            },
        ),
    ]
