# Generated by Django 5.2.7 on 2025-12-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'New order'), ('P', 'Processed'), ('S', 'Shipped order'), ('C', 'Completed order')], db_index=True, default='N', max_length=1),
        ),
    ]
