# Generated by Django 5.2.7 on 2025-11-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, default='user_pictures/default.png', upload_to='categories'),
        ),
    ]
