# Generated by Django 5.2.7 on 2025-11-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('N', 'New product'), ('O', 'Old product'), ('C', 'Comming soon product')], db_index=True, default='N', max_length=1),
        ),
    ]
