# Generated by Django 5.2.7 on 2026-01-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
