# Generated by Django 5.2.7 on 2025-11-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_contact_message'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='core_contac_email_cfac76_idx',
            old_name='core_contactm_email_idx',
        ),
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='core_contac_status_de41ec_idx',
            old_name='core_contactm_status_idx',
        ),
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='core_contac_created_63cb1b_idx',
            old_name='core_contactm_created_idx',
        ),
    ]
