# Generated by Django 5.2.7 on 2025-12-04 15:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_core_contactm_email_idx_core_contac_email_cfac76_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unsubscribed', 'Unsubscribed')], db_index=True, default='active', max_length=15)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['email'], name='core_newsle_email_144892_idx'), models.Index(fields=['status'], name='core_newsle_status_0a3bb7_idx'), models.Index(fields=['subscribed_at'], name='core_newsle_subscri_ef0604_idx')],
            },
        ),
    ]
