# Generated by Django 5.2.7 on 2025-12-04 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fas fa-question-circle', help_text='Font Awesome icon class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Help Category',
                'verbose_name_plural': 'Help Categories',
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['slug'], name='core_helpca_slug_96b783_idx'), models.Index(fields=['is_active'], name='core_helpca_is_acti_9a6b07_idx')],
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('unhelpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.helpcategory')),
            ],
            options={
                'verbose_name': 'Help Article',
                'verbose_name_plural': 'Help Articles',
                'ordering': ['category', 'order', 'title'],
                'indexes': [models.Index(fields=['slug'], name='core_helpar_slug_682aeb_idx'), models.Index(fields=['is_active'], name='core_helpar_is_acti_216227_idx'), models.Index(fields=['category'], name='core_helpar_categor_624c92_idx')],
            },
        ),
    ]
